### ISSUE TITLE
/docker-entrypoint.sh: line 14: /etc/go/log4j.properties: Permission denied

### ISSUE THREAD

**Issue by angeloneacsu** [unibet/docker-gocd-server#2]
Hello,

I've used the second docker-compose.yml (1 server and 1 agent) and it gives me the error:

Creating gocd_gocd-server_1
Creating gocd_gocd-agent_1
Attaching to gocd_gocd-server_1, gocd_gocd-agent_1
**gocd-server_1  | /docker-entrypoint.sh: line 14: /etc/go/log4j.properties: Permission denied**
gocd_gocd-server_1 exited with code 1
gocd-agent_1   | Waiting for https://gocd-server:8154/go
gocd-agent_1   | Waiting for https://gocd-server:8154/go
gocd-agent_1   | Waiting for https://gocd-server:8154/go

**Comment by karelbemelmans** [comment]
Can you provide us with some more information about your setup? 
It's working fine on my OSX laptop with the latest Docker CE edition.

**Comment by cevantes** [comment]
Same problem, /etc/go is owned by root, but the docker-entrypoint.sh wants to write to it as a non-root user. I only cloned the project and attempted `docker-compose up` in it. One unsafe workaround is to add `user: root` to docker-compose.yml...

**Comment by karelbemelmans** [comment]
Same question for you: show me some details about the setup you are running on (OS, Docker version, Docker compose version etc)

In the Dockerfile /etc/go is chown'd to go:go, so that should not give any issues in the entrypoint script. That folder is also volume mounted, perhaps there is a permission issue on the host your are mounting it on?

**Comment by cevantes** [comment]
here's a short demo script [reproduce-issue.txt](https://github.com/unibet/docker-gocd-server/files/1021973/reproduce-issue.txt)

**Comment by karelbemelmans** [comment]
Your go-data folders are owned by root, they should be owned by the non-privileged user created inside the Docker container, in this case uid 500 and gid 500.

**Comment by cevantes** [comment]
Exactly, this folder is created by docker, perhaps it should be taken care of automatically or you could mention it in Readme to avoid issues like this one, thank you.

**Comment by karelbemelmans** [comment]
I've update the README.md file with instructions on how to make sure these permissions are correct.

**Comment by cevantes** [comment]
Cheers!
